# Generated by Django 4.1.7 on 2023-05-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('address', models.CharField(max_length=64, verbose_name='address')),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Activated'), ('D', 'Deactivated')], default='A', max_length=1, verbose_name='status')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('content', models.CharField(max_length=2000, verbose_name='content')),
                ('view_count', models.IntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.place')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='PlaceBabyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramp', models.BooleanField(null=True)),
                ('baby_dish', models.BooleanField(null=True)),
                ('baby_chair', models.BooleanField(null=True)),
                ('nursing_room', models.BooleanField(null=True)),
                ('kids_room', models.BooleanField(null=True)),
                ('auto_door', models.BooleanField(null=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.place')),
            ],
        ),
    ]
