# Generated by Django 4.1.7 on 2023-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Activated'), ('D', 'Deactivated')], default='A', max_length=1, verbose_name='status')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('content', models.CharField(max_length=2000, verbose_name='content')),
                ('view_count', models.IntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'db_table': 'communities',
            },
        ),
    ]
