# Generated by Django 4.1.7 on 2023-05-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(default='free', max_length=10, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='community',
            name='comments_count',
            field=models.IntegerField(default=0, verbose_name='comments count'),
        ),
        migrations.AddField(
            model_name='community',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='like count'),
        ),
    ]
