# Generated by Django 4.1.7 on 2023-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='row_count',
            field=models.IntegerField(default=0, verbose_name='row count'),
        ),
    ]
