# Generated by Django 4.1.7 on 2023-04-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='idToken',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
