# Generated by Django 4.1.7 on 2023-05-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='baby_gender',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
