# Generated by Django 4.1.7 on 2023-04-17 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_remove_customuser_id_alter_customuser_idtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
