# Generated by Django 4.1.7 on 2023-04-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_customuser_idtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='idToken',
            new_name='id',
        ),
    ]
